# -*- coding: utf-8 -*-
"""fraudDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BgAKEpY8ba8d-JOqin26ExuJ89CRviY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("creditcard.csv")
df.head(5)

print(df.shape)
print(df.dtypes)
print(df.isnull().sum().max())
print(df['Class'].value_counts(),"fraud fraction",df['Class'].mean())

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

cols = [c for c in df.columns if c not in ['Time','Class']]
x=df[cols].values
y=df['Class'].values
x_scaled=StandardScaler().fit_transform(x)

#PCA
idx=np.random.RandomState(0).choice(len(x_scaled),size=min(10000,len(x_scaled)),replace=False)
x_pca=PCA(n_components=2).fit_transform(x_scaled[idx])
plt.scatter(x_pca[:,0],x_pca[:,1],s=6,c=y[idx])
plt.title("PCA 2D chart")
plt.show

# t-SNE (on very small sample)
idx2 = np.random.RandomState(1).choice(len(x_scaled), size=2000, replace=False)
plt.scatter(X_tsne[:,0], X_tsne[:,1], s=8, c=y[idx2])
plt.title("t-SNE (small sample)")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Separate features and labels
X = df.drop(columns=['Class'])
y = df['Class']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split (stratified to preserve fraud ratio)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, stratify=y, random_state=42
)

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    classification_report,
    confusion_matrix
)
import numpy as np

from sklearn.ensemble import IsolationForest

iso = IsolationForest(
    n_estimators=200,
    contamination=y_train.mean(),
    random_state=42
)
iso.fit(X_train)

iso_scores = -iso.decision_function(X_test)  # higher = more anomalous
iso_auc = roc_auc_score(y_test, iso_scores)
iso_ap = average_precision_score(y_test, iso_scores)

print("Isolation Forest ROC-AUC:", iso_auc)
print("Isolation Forest AP:", iso_ap)

threshold = np.percentile(iso_scores, 99.8)
iso_pred = (iso_scores >= threshold).astype(int)

print(confusion_matrix(y_test, iso_pred))
print(classification_report(y_test, iso_pred, digits=4))

k = 100
top_k_idx = np.argsort(iso_scores)[-k:]
precision_at_100 = y_test.iloc[top_k_idx].sum() / k
print("Isolation Forest Precision@100:", precision_at_100)

from sklearn.neighbors import LocalOutlierFactor

lof = LocalOutlierFactor(
    n_neighbors=20,
    contamination=y_train.mean()
)

lof_pred = lof.fit_predict(X_test)
lof_scores = -lof.negative_outlier_factor_

lof_auc = roc_auc_score(y_test, lof_scores)
lof_ap = average_precision_score(y_test, lof_scores)

print("LOF ROC-AUC:", lof_auc)
print("LOF AP:", lof_ap)

lof_binary = (lof_pred == -1).astype(int)
print(confusion_matrix(y_test, lof_binary))
print(classification_report(y_test, lof_binary, digits=4))

from sklearn.svm import OneClassSVM

# Use smaller subset (important)
X_train_small = X_train[:20000]
X_test_small = X_test[:10000]
y_test_small = y_test.iloc[:10000]

ocsvm = OneClassSVM(
    nu=y_train.mean(),
    kernel='rbf',
    gamma='auto'
)

ocsvm.fit(X_train_small)
svm_scores = -ocsvm.decision_function(X_test_small)

print("OCSVM ROC-AUC:", roc_auc_score(y_test_small, svm_scores))
print("OCSVM AP:", average_precision_score(y_test_small, svm_scores))

from tensorflow.keras import layers, models

input_dim = X_train.shape[1]

model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(input_dim,)),
    layers.Dense(32, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(input_dim)
])

model.compile(optimizer='adam', loss='mse')
model.fit(X_train, X_train, epochs=20, batch_size=256, validation_split=0.1)

recon = model.predict(X_test)
recon_error = np.mean((X_test - recon) ** 2, axis=1)

print("Autoencoder ROC-AUC:", roc_auc_score(y_test, recon_error))
print("Autoencoder AP:", average_precision_score(y_test, recon_error))

